inherit_from: .rubocop_todo.yml

AllCops:
    Exclude:
      - 'bin/*'
      - 'config/**/*'
      - 'db/**/*'
      - 'node_modules/**/*'
      - 'test/**/*'
      - 'Gemfile'
    TargetRubyVersion: 3.0

  Style/Documentation:
    Enabled: false

  Style/SymbolArray:
    Exclude:
      - 'Gemfile'